; configuration for LHS driver
[LHSconfig]
technique    = lhs
;technique    = random
;offset      = 0
seed        = 0
numSamples  = 3000
burnin      = 500  ;how long does it discard the data
serverList  = localhost:60001,localhost:60002,localhost:60003,localhost:60004,localhost:60005,localhost:60006,localhost:60007,localhost:60008,localhost:60009,localhost:60010
dataDir     = lhs_2010_07_04
scanMinima  = False
; scanMinima = True
; scanMinima creates a special batch where sequentially each of the parameters is set to its minimal value, if possible (e.g. for numerical values)
scanMinimaSamplesPerParam = 5
; number of random samples to generate of the other parameters when doing minima scan. overrideds numSamples.

; example
; [Param1] 		;name
; possible values       
; type	      = double  ;also: boolean,string,int
; dist        = normal  ;also: fixed, uniform, uniformrange, (future: zipf)
; mean        = 21000   ;only required for normal
; sd          = 100     ;only required for normal
; min         = 1000    ;optional for normal
; max         = 50000   ;optional for normal
; value       = 17.0    ;only for type fixed

; Structural				
[Population]
type = int
dist = Normal	
mean = 20000		
sd   = 10000
min  = 00000
max  = 40000

[AttritionRate]
type = double
dist = Normal
mean = 0.10
sd   = 0.04
min  = 0.02
max  = 0.18

[RadicalsAttritionIncrement]
type = double
dist = Normal
mean = 0.03
sd   = 0.01
min  = 0.01
max  = 0.05
      
[AvgPressurability]
type = double
dist = Normal
mean = 0.33
sd   = 0.20
min  = 0.00
max  = 0.73
      
[FractionInitRadicals]
type = double
dist = Normal
mean = 0.05
sd   = 0.05
min  = 0.00   
max  = 0.15

[FractionInitPacifists]
type = double
dist = Normal
mean = 0.05
sd   = 0.05
min  = 0.00
max  = 0.15

; Individual				
[NumFixedAttributes]
type = int
dist = Normal
mean = 5   
sd   = 2   
min  = 1   
max  = 9   

[NumVarAttributes]
type = int
dist = Normal
mean = 7   
sd   = 3   
min  = 1   
max  = 13  

[FixedAttribSalience]
type = double
dist = Normal
mean = 2.0 
sd   = 1.0 
min  = 0.0   
max  = 4.0 

[ZealSalience]
type = double
dist = Normal
mean = 2.0 
sd   = 1.0 
min  = 0.0   
max  = 4.0 

[NumMagnetsN]
type = int
dist = Uniform
min  = 0  
max  = 200 

[NumMagnetsR]
type = int
dist = Uniform
min  = 0   
max  = 50  

[NumMagnetsP]
type = int
dist = Uniform
min  = 0   
max  = 50  

[Diversity]	
type = double
dist = Normal
mean = 0.25
sd   = 0.10
min  = 0.05   
max  = 0.45

[MagneticEncounterRate]
type = double
dist = Normal
mean = 0.20
sd   = 0.10
min  = 0.00
max  = 0.40

[FractionExposedToMagnets]
type = double
dist = Normal
mean = 0.03
sd   = 0.03
min  = 0.00
max  = 0.09

; Network				
[AvgDegree]	
type = double
dist = Normal
mean = 5   
sd   = 5   
min  = 0   
max  = 15  

[RepellingTies]
type = boolean
dist = Fixed	
value= false		
      
[SafeNewFriends]
type = boolean
dist = Fixed	
value= true		

[TransitiveFriendship]
type = double
dist = Normal
mean = 0.50
sd   = 0.20
min  = 0.10
max  = 0.90

[AvgInitTieStrength]
type = double
dist = Normal
mean = 0.10
sd   = 0.10
min  = 0.00
max  = 0.30

;Superfluous for repellingTies == False
;[Disconnection Threshold]
;type = double
;dist = Uniform
;min  = 0.01
;max  = 0.10

[LinkAgeBonusFactor]	
type = double
dist = Normal
mean = 100
sd   = 50  
min  = 0 
max  = 200 

[MaxLinkAgeBonus]	
type = double
dist = Normal
mean = 1.0 
sd   = 1.0
min  = 0.0 
max  = 3.0   

;[Mutual Friends Factor]
;type = double
;dist = Normal
;mean = 1   
;sd   = 2   
;min  = 0   
;max  = 4   

; Implementation				
[RunLength]	
type = int
dist = fixed
value= 2000

[NetworkRecordTic]	
type = int
dist = fixed
value= -2

[NumZealLevels]	
type = int
dist = uniformrange			
range= 3
;we don't do 2 b/c it is not compatible with no moderates

[Rngseed]	
type = int
dist = uniformrange			
range= 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19

[DegreeSD]	
type = double
dist = Normal
mean = 1
sd   = 2
min  = 0
max  = 4

[InitTieStrengthSD]	
type = double
dist = Normal
mean = 0.05
sd   = 0.2
min  = 0.0 
max  = 0.45 

[PressurabilitySD]
type = double
dist = Normal
mean = 0.1
sd   = 0.1
min  = 0.0
max  = 0.3

[StrengthUpdateRate]
type = double
dist = Normal
mean = 0.2
sd   = 0.2
min  = 0.0
max  = 0.6

[SwitchRandomness]	
type = double
dist = Normal
mean = 0.1
sd   = 0.1
min  = 0.0
max  = 0.3

[SwitchPressFactor]	
type = double
dist = Normal
mean = 10.0
sd   = 20.0
min  = 0.5
max  = 50.0

[OutputDirectory]
dist = fixed
type = string
value= lhs_2010_07_04

[SimName]
dist = fixed
type = string
value= lhsSim

