; configuration for LHS driver
[LHSconfig]
technique    = lhs
;technique    = random
;offset      = 0
seed        = 0
numSamples  = 6000
burnin      = 500  ;how long does it discard the data
serverList  = localhost:60001,localhost:60002,localhost:60003,localhost:60004,localhost:60005,localhost:60006,localhost:60007,localhost:60008,localhost:60009,localhost:60010
dataDir     = lhs_2010_12_08
scanMinima  = False
; scanMinima = True
; scanMinima creates a special batch where sequentially each of the parameters is set to its minimal value, if possible (e.g. for numerical values)
scanMinimaSamplesPerParam = 5
; number of random samples to generate of the other parameters when doing minima scan. overrideds numSamples.

; example
; [Param1] 		;name
; possible values       
; type	      = double  ;also: boolean,string,int
; dist        = normal  ;also: fixed, uniform, uniformrange, (future: zipf)
; mean        = 21000   ;only required for normal
; sd          = 100     ;only required for normal
; min         = 1000    ;optional for normal
; max         = 50000   ;optional for normal
; value       = 17.0    ;only for type fixed

; Structural				
[Population]
type = int
dist = Normal	
mean = 10000		
sd   = 5000
min  = 1000
max  = 50000

[AttritionRate]
type = double
dist = Normal
mean = 0.10
sd   = 0.04
min  = 0.00
max  = 0.20

[RadicalsAttritionIncrement]
type = double
dist = Normal
mean = 0.03
sd   = 0.01
min  = -0.05
max  = 0.05
      
[AvgPressurability]
type = double
dist = Normal
mean = 0.33
sd   = 0.20
min  = 0.00
max  = 1.00
      
[FractionInitRadicals]
type = double
dist = Normal
mean = 0.05
sd   = 0.05
min  = 0.00   
max  = 0.50

[FractionInitPacifists]
type = double
dist = Normal
mean = 0.05
sd   = 0.05
min  = 0.00
max  = 0.50

; Individual				
[NumFixedAttributes]
type = int
dist = Normal
mean = 5   
sd   = 2   
min  = 0   
max  = 9   

[NumVarAttributes]
type = int
dist = Normal
mean = 7   
sd   = 3   
min  = 0   
max  = 12  

[FixedAttribSalience]
type = double
dist = Normal
mean = 2.0 
sd   = 1.0 
min  = 0   
max  = 10  

[ZealSalience]
type = double
dist = Normal
mean = 2.0 
sd   = 1.0 
min  = 0   
max  = 10  

[NumMagnetsN]
type = int
dist = Uniform
min  = 0  
max  = 200 

[NumMagnetsR]
type = int
dist = Uniform
min  = 0   
max  = 50  

[NumMagnetsP]
type = int
dist = Uniform
min  = 0   
max  = 50  

[Diversity]	
type = double
dist = Normal
mean = 0.25
sd   = 0.10
min  = 0   
max  = 0.50

[MagneticEncounterRate]
type = double
dist = Normal
mean = 0.20
sd   = 0.10
min  = 0.00
max  = 1.00

[FractionExposedToMagnets]
type = double
dist = Normal
mean = 0.03
sd   = 0.03
min  = 0.00
max  = 0.10

; Network				
[AvgDegree]	
type = double
dist = Normal
mean = 5   
sd   = 5   
min  = 0   
max  = 30  

[RepellingTies]
type = boolean
dist = Fixed	
value= false		
      
[SafeNewFriends]
type = boolean
dist = Fixed	
value= true		

[TransitiveFriendship]
type = double
dist = Normal
mean = 0.10
sd   = 0.10
min  = 0.00
max  = 1.00

[AvgInitTieStrength]
type = double
dist = Normal
mean = 0.10
sd   = 0.30
min  = 0.00
max  = 1.00

;Superfluous for repellingTies == False
;[Disconnection Threshold]
;type = double
;dist = Uniform
;min  = 0.01
;max  = 0.10

[LinkAgeBonusFactor]	
type = double
dist = Normal
mean = 100
sd   = 50  
min  = 0.1 
max  = 500 

[MaxLinkAgeBonus]	
type = double
dist = Normal
mean = 1.0 
sd   = 1.0
min  = 0   
max  = 3   

;[Mutual Friends Factor]
;type = double
;dist = Normal
;mean = 1   
;sd   = 2   
;min  = 0   
;max  = 4   

; Implementation				
[RunLength]	
type = int
dist = fixed
value= 1000

[NumZealLevels]	
type = int
dist = fixed			
value= 3
;dist = uniformrange			
;range= 3,5,7
;we don't do 2 b/c it is not compatible with no moderates

[Rngseed]	
type = int
dist = uniformrange			
range= 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19

[DegreeSD]	
type = double
dist = Normal
mean = 1
sd   = 2
min  = 0
max  = 10

[InitTieStrengthSD]	
type = double
dist = Normal
mean = 0.05
sd   = 0.2
min  = 0.0 
max  = 1.0 

[PressurabilitySD]
type = double
dist = Normal
mean = 0.1
sd   = 0.1
min  = 0.0
max  = 1.0

[StrengthUpdateRate]
type = double
dist = Normal
mean = 0.2
sd   = 0.2
min  = 0.00
max  = 1.00

[SwitchRandomness]	
type = double
dist = Normal
mean = 0.1
sd   = 0.1
min  = 0.0
max  = 0.5

[SwitchPressFactor]	
type = double
dist = Normal
mean = 10.0
sd   = 20.0
min  = 0.5
max  = 100

[OutputDirectory]
dist = fixed
type = string
value= lhs_2010_12_08

[SimName]
dist = fixed
type = string
value= lhsSim

